### ISSUE TITLE
PWA File System Support

### ISSUE THREAD

**Issue by jbdoderlein** [jbdoderlein/BetterOCaml#27]
Add PWA File System API and fallback for non compatible browser like firefox.
This [ponyfill](https://github.com/GoogleChromeLabs/browser-fs-access) seems a great solution

**Comment by jbdoderlein** [comment]
A bit difficult to implemant, and a bit useless

**Comment by Naereen** [comment]
I don't really understand what you would like to implement and why. Maybe it is (unfortunately) a bit useless?
