### ISSUE TITLE
Autosave in cache unsaved files

### ISSUE THREAD

**Issue by jbdoderlein** [jbdoderlein/BetterOCaml#28]
Add an autosave feature in localstorage
The document is saved every ~2 minutes and cache is delete when the editor is closed or the file is save

+ Maybe a quick save button in a corner of the editor ?

**Comment by jbdoderlein** [comment]
Done 👍 
in `1759acdba16da5e436b79cdefd9ce547de5d1c1a`

**Comment by Naereen** [comment]
Interesting feature!
