### ISSUE TITLE
Can't use input thing if I say cancel once

### ISSUE THREAD

**Issue by Butanium** [jbdoderlein/BetterOCaml#36]
Hey if I press the cancel (annuler) button while the intepreter asking for some input like this : 
![image](https://user-images.githubusercontent.com/55806347/116267020-4fb55800-a77c-11eb-9b12-85c413a3d867.png)
I have to refresh the page because I have an end_of_file error everytime I try to read new data after cancelling once : 
![image](https://user-images.githubusercontent.com/55806347/116267159-72477100-a77c-11eb-8191-1b575daf5801.png)
Reset the interpreter doesn't work and I have to refresh the page to make it working again... Until I press the cancel button again.

**Comment by math-gout** [comment]
Fixed here : 0b79c9a473cc1c0e2487a96847a59c4c4af98218
