### ISSUE TITLE
cannot load files into the interpreter

### ISSUE THREAD

**Issue by yuxiliu1995** [jbdoderlein/BetterOCaml#55]
If you create a new file named `myfile.ml`, then run this in the interpreter, you get:
```ocaml
#use "myfile.ml";;
Cannot find file myfile.ml
```

**Comment by jbdoderlein** [comment]
Fixed ! 
Commit : [9695c3afa92376f1df6be1a0b29788fbdf7d28df](https://github.com/jbdoderlein/BetterOCaml/commit/9695c3afa92376f1df6be1a0b29788fbdf7d28df)
