### ISSUE TITLE
wrong error message

### ISSUE THREAD

**Issue by ArtiskOnGit** [jbdoderlein/BetterOCaml#67]
Since last update, some errors (like  type errors) writes `exc during Lwt.async: "Assert_failure toplevel.ml:293:92"`  in the console instead of the usual error message.

Here is a screenshot of what I have tried :
![image](https://user-images.githubusercontent.com/57273190/139469045-4f478d93-d401-45e1-bfea-97f2d6a0f4b3.png)

**Comment by jbdoderlein** [comment]
Fixed in [f00c112](https://github.com/jbdoderlein/BetterOCaml/commit/f00c112a2e2af06b5d4ff9a868cb7ed907801209) ✅
