### ISSUE TITLE
Autocompletion enhancement

### ISSUE THREAD

**Issue by fksosn** [jbdoderlein/BetterOCaml#70]
When autocompletion is enabled, there is no way to temporarily block the enter key from applying the selected suggestion.
This leads to small object names at the end of a line being autocompleted instead of starting a new line.

This could be fixed with :
- autocompletion of user created object names
- the application of suggestions being done only with the 'tab' key (no more with 'return')
- the 'esc' key temporarily disabling autocompletion (longer than it already does)

**Comment by jbdoderlein** [comment]
I think the best solution to this problem is to extend the 'esc' effect, but I'll try the different possibilities and see which option is best.

I will work on this next week.

**Comment by jbdoderlein** [comment]
Fixed in [7083ea](https://github.com/jbdoderlein/BetterOCaml/commit/7083ea0e192d5323fec60ba4102444f8d9e6e765) ✅
