### ISSUE TITLE
Publish a new release with latest versions of the toplevel (4.14.1)

### ISSUE THREAD

**Issue by Naereen** [jbdoderlein/BetterOCaml#73]
Hi there @jbdoderlein,
Could you please publish a new release with the latest version of the toplevel?
Having the .zip file containing index.html file ready to be published is very convenient.
Thanks in advance.
Regards :smile:
@Naereen.

**Comment by jbdoderlein** [comment]
Hi @Naereen,
Sorry for the delay, I've just updated the repo and added a release with OCaml 1.14.1 : https://github.com/jbdoderlein/BetterOCaml/releases/tag/1.14.1
The release contains a zip ready to use !
